guc_search_api:
    path: /api/search
    controller: Guc\SearchBundle\Controller\SearchApiController
    methods: [GET]

guc_search_suggestions:
    path: /api/search/suggestions
    controller: Guc\SearchBundle\Controller\SearchSuggestionsController
    methods: [GET]
